# Generated by Django 5.0.2 on 2024-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
