# Generated by Django 5.0.2 on 2024-02-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
